[package]
name = "n3-sdl"
version = "0.1.0"
authors = ["Hilmar Wiegand <hilmar.wiegand@flameshome.net>"]

[dependencies]
time = "^0.1.36"

[dependencies.sdl2]
version = "^0.29.0"
default-features = false
features = ["image"]
